#define yy_create_buffer dis_ops_pddl_create_buffer
#define yy_delete_buffer dis_ops_pddl_delete_buffer
#define yy_scan_buffer dis_ops_pddl_scan_buffer
#define yy_scan_string dis_ops_pddl_scan_string
#define yy_scan_bytes dis_ops_pddl_scan_bytes
#define yy_flex_debug dis_ops_pddl_flex_debug
#define yy_init_buffer dis_ops_pddl_init_buffer
#define yy_flush_buffer dis_ops_pddl_flush_buffer
#define yy_load_buffer_state dis_ops_pddl_load_buffer_state
#define yy_switch_to_buffer dis_ops_pddl_switch_to_buffer
#define yyin dis_ops_pddlin
#define yyleng dis_ops_pddlleng
#define yylex dis_ops_pddllex
#define yyout dis_ops_pddlout
#define yyrestart dis_ops_pddlrestart
#define yytext dis_ops_pddltext
#define yywrap dis_ops_pddlwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
static yyconst short int yy_accept[353] =
    {   0,
       59,   59,    0,    0,    0,    0,   73,   71,   66,   64,
       71,    1,    2,   43,   42,   41,   59,   44,   59,   71,
       62,   36,   38,   40,   71,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   72,   63,   65,
       68,   67,   69,   70,   45,    0,    0,   59,   59,   59,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   62,   61,   37,   39,   58,   58,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       33,   57,   57,   57,   57,   57,   57,    0,    0,    0,
        0,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   58,   58,   57,   29,   57,    0,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   30,   57,
       57,   57,   57,   57,   57,    0,    0,    0,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       58,   57,   57,    0,    0,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   31,   57,
        0,   63,    0,    0,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   12,   58,   57,
       57,    0,    0,   57,   57,   57,   57,   57,   57,   57,
       32,   57,    0,   57,   57,   57,   57,    0,   67,    0,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,    6,   58,   22,   46,   55,    0,   57,   57,
        3,    4,   35,   34,   57,   57,   57,    0,   57,   57,
       57,   20,    0,   10,   57,   57,   57,   57,   57,   15,
       57,   57,   57,   57,   57,   57,   58,   57,    0,   57,
       57,   57,   57,   57,    0,   57,   57,   57,   57,   60,
       57,   57,   57,   17,   57,   57,   57,   16,   57,   57,
       57,   57,   58,   57,   54,   57,   50,   57,   57,   49,
       56,   57,   57,   47,   21,   57,   57,   57,   51,   57,
       57,   57,   57,   57,   57,   52,   57,   57,   57,   57,

       57,   57,   57,   14,    7,   57,   57,    9,   57,   57,
       57,   57,   57,   57,   28,   57,   19,   48,   57,   57,
       57,   57,   11,   57,    8,   57,   57,   57,   27,   57,
       57,   18,   57,   57,   57,   57,   23,   57,   57,   57,
       13,    5,   26,   57,   57,   57,   24,   57,   57,   25,
       53,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   30,
       45,    1,   45,   46,   47,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   30,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    1,    2
    } ;

static yyconst short int yy_base[361] =
    {   0,
        0,    0,   45,   46,   49,   51,  418,  419,  419,  419,
      378,  419,  419,  419,  419,   58,  402,  419,   41,   52,
      412,  396,  419,  395,  388,   30,    0,   72,  368,  376,
      375,   34,  374,   61,  370,   76,   72,  360,  419,  359,
      358,  419,  357,  356,  419,  101,  105,  387,   99,  386,
      376,    0,  364,   79,  371,  356,  363,   91,  369,  349,
      371,  388,  419,  419,  419,    0,  350,    0,  347,  364,
      349,   60,   91,  354,  356,  347,  352,  347,  358,  341,
        0,  354,  353,  356,  344,  350,  335,  368,  365,  114,
      342,  331,  336,  331,  330,  340,  332,  329,  326,  337,

      325,  325,  322,    0,  321,  336,    0,  327,   95,  323,
      317,  324,  331,  313,  329,  325,  317,  310,    0,  309,
      319,  313,  318,  309,  313,  337,  331,  299,  308,   91,
      307,  314,  309,  310,  301,  310,   98,  290,  304,  290,
      306,  282,  298,  291,  284,  288,  296,  287,  290,  279,
      286,  305,  271,  289,  309,  287,  286,  271,    0,  280,
      262,  419,  304,  278,  271,  275,  264,  261,  262,  277,
      260,  269,  265,  262,  266,  265,  255,    0,  253,  253,
      257,  265,  267,  249,  265,  260,  251,  245,  251,  102,
        0,  260,  259,  242,  267,  248,  243,  229,  419,  249,

      240,  233,  103,  246,  241,  230,  239,  242,  241,  232,
      241,  226,    0,  233,  250,    0,  419,  223,  220,  220,
        0,    0,    0,    0,  231,  216,  217,  223,  228,  101,
      220,    0,  214,    0,  221,  216,  227,  223,   93,    0,
      212,  207,  205,  219,  221,  216,  206,  197,  199,  226,
      211,  196,  197,  208,  201,  198,  196,  194,  203,  419,
      193,  187,  196,    0,  191,  198,  189,    0,  196,  191,
      180,  186,  184,  187,  419,  181,    0,  189,  184,    0,
      419,  189,  169,    0,  199,  176,  170,  174,    0,  195,
      167,  167,  164,  177,  176,    0,  161,  166,  161,  164,

      171,  162,  110,    0,    0,  155,  172,    0,  154,  162,
      152,  156,  160,  164,    0,  159,    0,    0,  159,  159,
      145,  159,    0,  147,    0,  141,  150,  153,    0,  138,
      150,    0,  136,  141,  135,  139,    0,  146,  136,  140,
        0,    0,    0,  131,  130,  104,    0,  112,  103,    0,
        0,  419,  141,  145,  149,  132,  152,  154,  158,  162
    } ;

static yyconst short int yy_def[361] =
    {   0,
      352,    1,  353,  353,  354,  354,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      355,  352,  352,  352,  356,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  355,  352,  352,  352,  358,  358,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  352,  352,  352,
      352,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  358,  358,  357,  357,  357,  352,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  359,  352,  352,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      358,  357,  357,  352,  352,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      352,  352,  360,  352,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  358,  357,
      357,  352,  352,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  352,  357,  357,  357,  357,  352,  352,  352,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  358,  357,  357,  352,  352,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  352,  357,  357,
      357,  357,  352,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  358,  357,  352,  357,
      357,  357,  357,  357,  352,  357,  357,  357,  357,  352,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  358,  357,  352,  357,  357,  357,  357,  357,
      352,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  358,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,    0,  352,  352,  352,  352,  352,  352,  352,  352
    } ;

static yyconst short int yy_nxt[467] =
    {   0,
        8,    8,    9,    8,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   27,   28,   29,   30,   27,   31,   32,   27,
       27,   27,   33,   34,   35,   27,   27,   36,   27,   27,
       27,   37,   27,   27,    8,    8,    8,   39,   39,   40,
       40,   42,   48,   42,   49,   43,   44,   43,   44,   46,
       69,   46,   70,  109,   47,   78,   79,   71,   72,   48,
      110,   49,   51,   52,   53,   54,   55,   56,   52,   52,
       57,   52,   52,   52,   52,   52,   58,   52,   59,   52,
       60,   52,   61,   52,   52,   52,   73,   81,   84,   86,

       87,   82,   46,   94,   46,   74,   90,   47,   90,   85,
       48,   99,   49,  111,  166,   90,  112,   90,   95,  144,
      174,  175,  225,  236,  257,  226,  265,  100,  167,   91,
      319,  320,  145,  266,   66,  351,  350,  349,   91,  237,
      258,   38,   38,   38,   38,   41,   41,   41,   41,   62,
       62,   62,   62,   68,   68,  104,  104,  104,  161,  161,
      161,  161,  198,  198,  198,  198,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  318,  317,  316,  315,  314,  313,

      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  264,  263,  262,  261,
      260,  259,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  235,  234,  233,   89,  232,  231,  230,  229,  228,
      227,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,

      205,  204,  203,  202,  201,  200,  199,   88,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      173,  172,  171,  170,  169,  168,  165,  164,  163,  162,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  108,  107,  106,  105,
       63,  103,  102,  101,   98,   97,   96,   93,   92,   50,

       50,   89,   89,   89,   88,   88,   83,   80,   77,   76,
       75,   67,   65,   64,   63,   50,   45,  352,    7,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352
    } ;

static yyconst short int yy_chk[467] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    5,   19,    6,   19,    5,    5,    6,    6,   16,
       26,   16,   26,   72,   16,   32,   32,   26,   26,   16,
       72,   16,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   28,   34,   36,   37,

       37,   34,   46,   54,   46,   28,   47,   46,   47,   36,
       49,   58,   49,   73,  130,   90,   73,   90,   54,  109,
      137,  137,  190,  203,  230,  190,  239,   58,  130,   47,
      303,  303,  109,  239,  356,  349,  348,  346,   90,  203,
      230,  353,  353,  353,  353,  354,  354,  354,  354,  355,
      355,  355,  355,  357,  357,  358,  358,  358,  359,  359,
      359,  359,  360,  360,  360,  360,  345,  344,  340,  339,
      338,  336,  335,  334,  333,  331,  330,  328,  327,  326,
      324,  322,  321,  320,  319,  316,  314,  313,  312,  311,
      310,  309,  307,  306,  302,  301,  300,  299,  298,  297,

      295,  294,  293,  292,  291,  290,  288,  287,  286,  285,
      283,  282,  279,  278,  276,  274,  273,  272,  271,  270,
      269,  267,  266,  265,  263,  262,  261,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  238,  237,  236,  235,
      233,  231,  229,  228,  227,  226,  225,  220,  219,  218,
      215,  214,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  202,  201,  200,  198,  197,  196,  195,  194,  193,
      192,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  177,  176,  175,  174,  173,  172,  171,  170,

      169,  168,  167,  166,  165,  164,  163,  161,  160,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      136,  135,  134,  133,  132,  131,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  108,  106,  105,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   89,   88,   87,   86,   85,   84,   83,   82,   80,
       79,   78,   77,   76,   75,   74,   71,   70,   69,   67,
       62,   61,   60,   59,   57,   56,   55,   53,   51,   50,

       48,   44,   43,   41,   40,   38,   35,   33,   31,   30,
       29,   25,   24,   22,   21,   17,   11,    7,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex-ops_pddl.l"
#define INITIAL 0
#line 2 "lex-ops_pddl.l"
#include "dis_ff.h"
#include "dis_parse.h"

/* default yywrap function - always treat EOF as an EOF  */
#define dis_ops_pddlwrap() 1 

#define COMMENT 1
#define OVERREAD 2

#line 609 "lex.dis_ops_pddl.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 39 "lex-ops_pddl.l"


#line 763 "lex.dis_ops_pddl.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 353 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 419 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "lex-ops_pddl.l"
{  return(OPEN_PAREN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "lex-ops_pddl.l"
{  return(CLOSE_PAREN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "lex-ops_pddl.l"
{  return(DEFINE_TOK); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "lex-ops_pddl.l"
{  return(DOMAIN_TOK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "lex-ops_pddl.l"
{  return(REQUIREMENTS_TOK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "lex-ops_pddl.l"
{  return(TYPES_TOK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "lex-ops_pddl.l"
{  return(CONSTANTS_TOK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "lex-ops_pddl.l"
{ return(PREDICATES_TOK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "lex-ops_pddl.l"
{ return(FUNCTIONS_TOK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "lex-ops_pddl.l"
{  return(ACTION_TOK); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "lex-ops_pddl.l"
{  return(PARAMETERS_TOK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "lex-ops_pddl.l"
{ return(VARS_TOK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "lex-ops_pddl.l"
{  return(PRECONDITION_TOK); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "lex-ops_pddl.l"
{ return(CONDITION_TOK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "lex-ops_pddl.l"
{  return(EFFECT_TOK); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "lex-ops_pddl.l"
{  return(IMPLIES_TOK); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "lex-ops_pddl.l"
{ return(DERIVED_TOK); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "lex-ops_pddl.l"
{ return(CONSTRAINTS_TOK); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "lex-ops_pddl.l"
{ return(PREFERENCE_TOK); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "lex-ops_pddl.l"
{ return(WITHIN_TOK); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "lex-ops_pddl.l"
{ return(SOMETIME_TOK); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "lex-ops_pddl.l"
{ return(ALWAYS_TOK); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "lex-ops_pddl.l"
{ return AT_MOST_ONCE_TOK; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "lex-ops_pddl.l"
{ return SOMETIME_AFTER_TOK; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "lex-ops_pddl.l"
{ return SOMETIME_BEFORE_TOK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "lex-ops_pddl.l"
{ return ALWAYS_WITHIN_TOK; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "lex-ops_pddl.l"
{ return HOLD_DURING_TOK; }  
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "lex-ops_pddl.l"
{ return HOLD_AFTER_TOK; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "lex-ops_pddl.l"
{  return(dis_AND_TOK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "lex-ops_pddl.l"
{  return(dis_NOT_TOK); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "lex-ops_pddl.l"
{  return(dis_WHEN_TOK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "lex-ops_pddl.l"
{  return(IMPLY_TOK); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "lex-ops_pddl.l"
{  return(dis_OR_TOK); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "lex-ops_pddl.l"
{  return(Fdis_ORdis_ALL_TOK); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "lex-ops_pddl.l"
{  return(dis_EXISTS_TOK); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "lex-ops_pddl.l"
{  return(LE_TOK); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "lex-ops_pddl.l"
{  return(LEQ_TOK); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "lex-ops_pddl.l"
{  return(EQ_TOK); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 "lex-ops_pddl.l"
{  return(GEQ_TOK); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "lex-ops_pddl.l"
{  return(GE_TOK); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "lex-ops_pddl.l"
{  return(MINUS_TOK); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "lex-ops_pddl.l"
{  return(AD_TOK); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "lex-ops_pddl.l"
{  return(MU_TOK); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "lex-ops_pddl.l"
{  return(DI_TOK); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "lex-ops_pddl.l"
{ return (TIME_TOK);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "lex-ops_pddl.l"
{ return(ASSIGN_TOK); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 123 "lex-ops_pddl.l"
{ return(SCALE_UP_TOK); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "lex-ops_pddl.l"
{ return(SCALE_DOWN_TOK); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 127 "lex-ops_pddl.l"
{ return(INCREASE_TOK); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "lex-ops_pddl.l"
{ return(DECREASE_TOK); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 131 "lex-ops_pddl.l"
{ return (DURATION_TOK); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 133 "lex-ops_pddl.l"
{  return(DURATION_VAR_TOK); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "lex-ops_pddl.l"
{ return (DURATIVE_ACTION_TOK); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 137 "lex-ops_pddl.l"
{return AT_START;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "lex-ops_pddl.l"
{return AT_END;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "lex-ops_pddl.l"
{return OVER_ALL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 144 "lex-ops_pddl.l"
{ dis_strupcase(yytext); strcpy(yylval.string, yytext); 
 return(NAME); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 147 "lex-ops_pddl.l"
{ dis_strupcase(yytext); strcpy(yylval.string, yytext); 
 return(VARIABLE); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 150 "lex-ops_pddl.l"
{ strcpy(yylval.string, yytext); return(NUM);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 153 "lex-ops_pddl.l"
{ return(EITHER_TOK); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 155 "lex-ops_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 156 "lex-ops_pddl.l"
{  /* this will hold only in files that end with
		   a comment but no linefeed */ } 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 159 "lex-ops_pddl.l"
{  dis_lineno++; }  ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "lex-ops_pddl.l"
{ BEGIN COMMENT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "lex-ops_pddl.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "lex-ops_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 167 "lex-ops_pddl.l"
{  dis_lineno++; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "lex-ops_pddl.l"
{  }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "lex-ops_pddl.l"
{  BEGIN OVERREAD; dis_gbracket_count++; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 173 "lex-ops_pddl.l"
{  BEGIN OVERREAD; dis_gbracket_count--; 
  if (!dis_gbracket_count) BEGIN INITIAL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 176 "lex-ops_pddl.l"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 177 "lex-ops_pddl.l"
ECHO;
	YY_BREAK
#line 1210 "lex.dis_ops_pddl.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(OVERREAD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 353 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 353 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 352);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 177 "lex-ops_pddl.l"

